Mysite/Mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

Mysite/main/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('<int:id>', views.index, name='index'),
    path('', views.home, name='home'),
    path('create/', views.create, name='create'),
    ]

Mysite/main/models.py
from django.db import models


class ToDoList(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Item(models.Model):
    todolist = models.ForeignKey(ToDoList, on_delete=models.CASCADE)
    text = models.CharField(max_length=300)
    complete = models.BooleanField()

    def __str__(self):
        return self.text

Mysite/main/forms.py
from django import forms

class CreateNewList(forms.Form):
    name = forms.CharField(label='Name', max_length=200)
    check = forms.BooleanField()

Mysite/main/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from .models import ToDoList, Item
from .forms import CreateNewList


def index(response, id):
    ls = ToDoList.objects.get(id=id)
    return render(response, "main/base.html", {"ls":ls})


def home(response):
    return render(response, "main/home.html", {})


def create(response):
    if response.method == 'POST':
        form = CreateNewList()
        
        if form.is_valid():
            n = form.cleaned_data['name']
            t = ToDoList(name=n)
            t.save()
        
        return HttpResponseRedirect("/%i", "%t.id")
        
    else:
        form = CreateNewList()
    return render(response, "main/create.html", {'form':form})

Mysite/main/templates/main/base.html
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Minha base template</title>
</head>
<body>
<h1>{% block title %} BASE DO SITE {% endblock %}</h1>
<div>
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

Mysite/main/templates/main/create.html
{% extends 'main/base.html' %}

{% block title %} Create New List {% endblock %}

{% block content %}
Create Page
<form method="post" action="/create/">
    {% csrf_token %} <!--Adicionando token para conseguir finalizar o processo-->
    {{form.as_p}} <!-- Adicionando um forms (do Django)-->
    <button type="submit" name="save">
        Create New
    </button>

</form>
{% endblock %}

Mysite/main/templates/main/home.html
{% extends "main/base.html" %}

{% block title %}
HOME DO SITE
{% endblock %}
{% block content %}
{% for c in range(10) %}
    {% <p>c</p>%}
{% endfor %}
<h1>Home Page</h1>
{% endblock %}

Mysite/main/templates/main/list.html
{% extends "main/base.html" %}

{% block title %} View List {% endblock %}


{% block content %}
    <h1>{{ ls.name }}</h1>
        <ul>
            {% for item in ls.item_set.all %}
                {% if item.complete == True %}
                    <li>{{ item.text }}</li>
                {% endif %}
            {% endfor %}
        </ul>
{% endblock %}